FROM oven/bun:1.3.5-alpine AS build
WORKDIR /usr/src/app

FROM build AS dependencies
RUN mkdir -p /temp

COPY package.json bun.lock /temp/
RUN cd /temp && bun install --frozen-lockfile --production

FROM build AS release
COPY --from=dependencies /temp/node_modules ./node_modules

RUN apk add --no-cache curl
COPY --chown=bun:bun . .

USER bun
EXPOSE 3000
ENTRYPOINT [ "bun", "run", "prod" ]
