FROM oven/bun:1.3.9-alpine AS base
WORKDIR /usr/src/app

# === Dependencies Stage ===
FROM base AS dependencies
COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

# === Development Stage ===
FROM dependencies AS development
COPY . .
USER bun

EXPOSE 3000
ENTRYPOINT [ "bun", "run", "start" ]
