services:
  postgres:
    env_file: ../.env.local
    image: postgres:16-alpine
    restart: unless-stopped
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - sockets-network
    volumes:
      - sockets-pg-data:/var/lib/postgresql/data
    healthcheck: # Use pg_isready to check if the database is ready
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 5
